const Products = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    fatherName: "Robert Doe",
    address: "123 Main St, Anytown, USA",
    gmail: "john.doe@gmail.com",
    phoneNumber: "123-456-7890",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    fatherName: "Michael Smith",
    address: "456 Elm St, Othertown, USA",
    gmail: "jane.smith@gmail.com",
    phoneNumber: "234-567-8901",
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    fatherName: "David Johnson",
    address: "789 Oak St, Anothertown, USA",
    gmail: "alice.johnson@gmail.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Brown",
    fatherName: "James Brown",
    address: "101 Pine St, Sometown, USA",
    gmail: "bob.brown@gmail.com",
    phoneNumber: "456-789-0123",
  },
  {
    id: 5,
    firstName: "Emily",
    lastName: "Davis",
    fatherName: "Richard Davis",
    address: "202 Cedar St, Mytown, USA",
    gmail: "emily.davis@gmail.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 6,
    firstName: "Michael",
    lastName: "Miller",
    fatherName: "Charles Miller",
    address: "303 Birch St, Yourtown, USA",
    gmail: "michael.miller@gmail.com",
    phoneNumber: "678-901-2345",
  },
  {
    id: 7,
    firstName: "Sarah",
    lastName: "Wilson",
    fatherName: "George Wilson",
    address: "404 Spruce St, Theirtown, USA",
    gmail: "sarah.wilson@gmail.com",
    phoneNumber: "789-012-3456",
  },
  {
    id: 8,
    firstName: "David",
    lastName: "Moore",
    fatherName: "Joseph Moore",
    address: "505 Maple St, Histown, USA",
    gmail: "david.moore@gmail.com",
    phoneNumber: "890-123-4567",
  },
  {
    id: 9,
    firstName: "Laura",
    lastName: "Taylor",
    fatherName: "Thomas Taylor",
    address: "606 Walnut St, Hertown, USA",
    gmail: "laura.taylor@gmail.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 10,
    firstName: "James",
    lastName: "Anderson",
    fatherName: "William Anderson",
    address: "707 Chestnut St, Thistown, USA",
    gmail: "james.anderson@gmail.com",
    phoneNumber: "012-345-6789",
  },
];
module.exports = Products;
